
export const SET_DB_DATE = 'SET_DB_DATE';
export const SET_CURRENT_BRANCH = 'SET_CURRENT_BRANCH';

export const LOCATIONS_LOAD = 'LOCATIONS_LOAD';
export const LOCATIONS_LOAD_SUCCESS = 'LOCATIONS_LOAD_SUCCESS';
export const LOCATIONS_LOAD_FAILURE = 'LOCATIONS_LOAD_FAILURE';
